name: VitalMail
version: @version@
main: com.tamrielnetwork.vitalhome.VitalMail
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to set homes and teleport to them.
commands:
  mail:
    description: "Main command"
    usage: "/home"
permissions:
  vitalmail.send:
    description: "Permission to send mail"
    default: op
  vitalmail.read:
    description: "Permission to read mail"
    default: op
  vitalmail.clear:
    description: "Permission to clear mail)"
    default: op
  vitalmail.cooldown.bypass:
    description: "Bypass cooldown"
    default: op